name: Ideal Travel Creations

on:
  push:
    branches: [main]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
            node-version: "14"
            check-latest: true
          
      - name: Install yarn globally
        run: npm install -g yarn
      
      - name: Install zip unzip
        run: sudo apt install zip unzip

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_USERNAME: ${{ secrets.USERNAME }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
          envkey_MAPBOX_API: ${{ secrets.MAPBOX_API }}
          envkey_REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
          envkey_BACKEND_URL: ${{ secrets.BACKEND_URL }}
          directory: ./
          file_name: .env.production
          fail_on_empty: false

      - name: Install yarn packages
        run: yarn
  
      - name: Run `yarn build` to buidl the code
        run: yarn build

      - name: Remove root node_modules
        run: sudo rm -rf node_modules

      - name: Make the zip file
        run: zip -r ./output.zip ./

      - name: Create a new folder to store the zip file
        run: mkdir ../code

      - name: Move the zip file to the new created folder
        run: mv ./output.zip ../code

      - name: Enter S3 Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-1"
      
      - name: Upload to S3
        run: aws s3 sync ../code s3://${{ secrets.AWS_S3_BUCKET_NAME }}
                    
      - name: Pull S3 code and run ./run.sh
        uses: appleboy/ssh-action@master
        env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.PORT }}
          envs: AWS_S3_BUCKET
          script: |
            cd /home/ubuntu/
            curl --silent https://gist.githubusercontent.com/utkarshk384/7ef53cba4cf342bb90e439895318f3d3/raw/c3fa1c9a2529354c209e2c5f5e0f743c3d3cda36/update.sh > update.sh
            sudo chmod +x ./update.sh
            ./update.sh ideal-travel-creations ideal-travel-creations-bucket 
