name: Ideal Travel Creations

on:
  push:
    branches: [main]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2
        with:
            node-version: "14"
            check-latest: true

      - name: Build Zip file
        run: mkdir code
      - run: git archive HEAD -o ./code/itc.zip

      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-1"
      - run: aws s3 sync ./code s3://${{ secrets.AWS_S3_BUCKET_NAME }}
                    
      - name: Pull S3 code and run ./run.sh
        uses: appleboy/ssh-action@master
        env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.PORT }}
          envs: AWS_S3_BUCKET
          script: |
            cd /home/ubuntu/
            sudo apt-get install awscli -y
            aws s3 cp s3://$AWS_S3_BUCKET/itc.zip /home/ubuntu/itc.zip
            mkdir temp
            unzip ./itc.zip -d ./temp/
            mv ./temp/scripts/run.sh ./
            sudo chmod +x ./run.sh
            ./run.sh
